let actDict = {
  1: {
    name: 'outdoor walk with friend',
    // number: 1,
    category: 'social',
    points: 500,
    description: "Want some light exercise, but feel like it won’t be fun alone? Try taking a walk outside with a buddy: the extra company can make things less mundane. And, in addition to exercise, you may also get the benefits of enjoyable and/or interesting conversations, time for bonding with your buddy, and a nice change of pace from other happenings in your day-to-day life.",
    instruction: '- find a willing buddy (friend, family member, significant other, neighbor, etc)\n- determine the route for your walk: you don’t need an exact route, but make sure that either you or your buddy are already fairly familiar with the area of your walk\n- enjoy your walk! Take your time and make the most of this opportunity that you have with your buddy and are outside.',
    tips: '- be sure to check the weather before the time of the walk\n- time-permitting, you and your buddy may want to try venturing into slightly more unfamiliar territory',
  },
  2: {
    name: 'picnic',
    // number: 2,
    category: 'social',
    points: 200,
    description: '',
    instruction: '',
    tips: '',
  },
  3: {
    name: 'play catch',
    // number: 3,
    category: 'social',
    points: 100,
    description: '',
    instruction: '',
    tips: '',
  },
  4: {
    name: 'go to park with friends',
    // number: 4,
    category: 'social',
    points: 200,
    description: '',
    instruction: '',
    tips: '',
  },
  5: {
    name: 'create sidewalk art with friends',
    // number: 5,
    category: 'social',
    points: 400,
    description: '',
    instruction: '',
    tips: '',
    },
  6: {
    name: 'outdoor run',
    // number: 6,
    category: 'exercise',
    points: 400,
    description: 'Outdoor runs are a great source of cardio while also enjoying the outdoors. ',
    instruction: '- To prepare, check the weather for the time you will be on the run, grab your running shoes, and put on an athletic outfit that you will be comfortable in and/or motivates you.\n- Go on the run! Listen to your body! Do not ignore signs of early injuries. Make sure to adjust your run and expectations based on how your body feels.\n- Make sure to stretch after you run to avoid stiffness and soreness the next day! This also helps prevent injuries!',
    tips: '- If you run regularly, stop by a running store in your neighborhood to find the proper shoes for you. Using improper shoes can result in longer recoveries and higher chance of injury.\n- Do not skimp on recovery time!'

  },
  7: {
    name: 'solo walk',
    // number: 7,
    category: 'exercise',
    points: 200,
    description: '',
    instruction: '',
    tips: '',
  },
  8: {
    name: 'bike ride',
    // number: 8,
    category: 'exercise',
    points: 100,
    description: '',
    instruction: '',
    tips: '',
  },
  9: {
    name: 'yoga',
    // number: 9,
    category: 'exercise',
    points: 200,
    description: '',
    instruction: '',
    tips: '',
  },
  10: {
    name: 'shoot hoops',
    // number: 10,
    category: 'exercise',
    points: 100,
    description: '',
    instruction: '',
    tips: '',
  },
  11: {
    name: 'outdoor meditation',
    // number: 11,
    category: 'mental',
    points: 200,
    description: '',
    instruction: '',
    tips: '',
  },
  12: {
    name: 'nature scavenger hunt',
    // number: 12,
    category: 'mental',
    points: 200,
    description: '',
    instruction: '',
    tips: '',
  },
  13: {
    name: 'read book outside',
    // number: 13,
    category: 'mental',
    points: 100,
    description: '',
    instruction: '',
    tips: '',
  },
  14: {
    name: 'Do HW outside',
    // number: 14,
    category: 'mental',
    points: 200,
    description: '',
    instruction: '',
    tips: '',
  },
  15: {
    name: 'Bird watching',
    // number: 15,
    category: 'mental',
    points: 100,
    description: '',
    instruction: '',
    tips: '',
  },
};

export function getActInfo() {
  return actDict;
}
