let actDict = {
  1: {
    name: 'outdoor walk with friend',
    // number: 1,
    category: 'social',
    points: 500,
    description: "Want some light exercise, but feel like it won’t be fun alone? Try taking a walk outside with a buddy: the extra company can make things less mundane. And, in addition to exercise, you may also get the benefits of enjoyable and/or interesting conversations, time for bonding with your buddy, and a nice change of pace from other happenings in your day-to-day life.",
    instruction: '- find a willing buddy (friend, family member, significant other, neighbor, etc)\n- determine the route for your walk: you don’t need an exact route, but make sure that either you or your buddy are already fairly familiar with the area of your walk\n- enjoy your walk! Take your time and make the most of this opportunity that you have with your buddy and are outside.',
    tips: '- be sure to check the weather before the time of the walk\n- time-permitting, you and your buddy may want to try venturing into slightly more unfamiliar territory',
  },
  2: {
    name: 'picnic',
    // number: 2,
    category: 'social',
    points: 600,
    description: 'Is there anything better than food and the outdoors? Why not bring those two together? Picnic is a wonderful activity where you enjoy simple foods with your friends as you enjoy the outdoors. ',
    instruction: '- Assign each friend to prepare a snack or a meal for the whole group to enjoy.\n- Pack towels to sit on and bing bags for cleanup\n- Gather your friends and locate a park that you can all enjoy\n- Enjoy the fun conversations and delicious food!\n- Do NOT forget to clean up after yourself! We must take care of our environment.',
    tips: '- Food attracts ants and other bugs. Make sure to bring bug spray to protect yourself from these not-so-pleasurable outdoor creatures.\n- Keep the food simple! Your friends will be more excited to join an event where not much is asked of them. Simple foods are also easier to clean up and carry around!',
  },
  3: {
    name: 'play catch',
    // number: 3,
    category: 'social',
    points: 200,
    description: "You don't need to be a baseball or a softball player to enjoy a relaxing game of catch! If you have gloves and a baseball/softball ball, use those to protect your hands. If you don't, just use a tennis ball to toss it between your friends. Conversations flow very nicely when you are all participating in a casual activity together.",
    instruction: "- Grab a tennis ball (or a softball/baseball ball if you have the proper gloves)\n- Find a park that is not too far from all of your friends\n- Distance one another so there is enough distance to throw the ball without making it too difficult or competitive\n- Toss the ball back and forth between your friends as you chat about your day and any thoughts you have been sitting on!",
    tips: "- It is easy to get carried away in your conversation and forget about the fact that you are throwing a ball at someone or a ball is being thrown at you! Stay alert and aware while playing without getting lost in the conversation!\n- This is not a competition! The main objective of this is to enjoy the outdoors with your friends, not show off your throwing skills!",
  },
  4: {
    name: 'go to park with friends',
    // number: 4,
    category: 'social',
    points: 100,
    description: 'Nothing beats enjoying the great outdoors--and maybe playing some games--with a few of your best friends. Time to get in contact, find your local park, and catch up outside!',
    instruction: "- Get in contact with a few of your friends, and invite them to join you for a day at a park\n- Pick a park that is centrally located--this makes it easy for everyone\n- Discuss what you wanna do while you’re there--maybe bring a ball?\n- Finally, settle on a time that works best for all of you, and enjoy your time outside!",
    tips: 'Many parks have outdoor water fountains, but during the winter they often shut these down. Just in case, it is always best to bring a water bottle of your own.',
  },
  5: {
    name: 'create sidewalk art with friends',
    // number: 5,
    category: 'social',
    points: 300,
    description: "For a crafty project that also gets you outside, try creating sidewalk art! As you can imagine, with endless sidewalk, chalk, and ideas the possibilities are endless. Put your imagination at the forefront of your day and make the neighborhood brighter with your artistic ideas!",
    instruction: "- Grab some chalk (Walmart has very affordable, bright options)\n- Find smooth patch on the sidewalk\n- Draw anything that comes to your mind!",
    tips: "- Do not be hard on yourself! If you mess up your art, chalk is easily cleaned with water! Grab a sponge and touch up your art or wait for the rain to try again on a clean, new canvas.\n- Check with your neighbors before getting carried away and moving on to their sidewalk after you have covered yours.",
    },
  6: {
    name: 'outdoor run',
    // number: 6,
    category: 'exercise',
    points: 400,
    description: 'Outdoor runs are a great source of cardio while also enjoying the outdoors. ',
    instruction: '- To prepare, check the weather for the time you will be on the run, grab your running shoes, and put on an athletic outfit that you will be comfortable in and/or motivates you.\n- Go on the run! Listen to your body! Do not ignore signs of early injuries. Make sure to adjust your run and expectations based on how your body feels.\n- Make sure to stretch after you run to avoid stiffness and soreness the next day! This also helps prevent injuries!',
    tips: '- If you run regularly, stop by a running store in your neighborhood to find the proper shoes for you. Using improper shoes can result in longer recoveries and higher chance of injury.\n- Do not skimp on recovery time!'

  },
  7: {
    name: 'solo walk',
    // number: 7,
    category: 'exercise',
    points: 300,
    description: "Walking alone is a great way to reset your mind. You can do this activity at your own schedule and pace. This is a great opportunity to be alone with your thoughts to process your emotions, or even change your emotions for the better.",
    instruction: "- Put on comfortable walking shoes\n- Let someone you know that you are heading out\n- Bring a phone and pepper spray if possible\n- Pick a path you are familiar with\n- Enjoy the outdoors!\n- When youre are back, let the individual from step 2 know that you are back at home!",
    tips: "Practice safety when walking alone! Trust your instincts: If you feel unsafe or uncomfortable, act to protect yourself. This may include turning around, going another way, crossing a street, calling for help, screaming, or running away.",
  },
  8: {
    name: 'bike ride',
    // number: 8,
    category: 'exercise',
    points: 400,
    description: "Riding a bike is a fun and productive way to get to see your city! Whether you go for a leisurely pedal or a sprightly ride, you are sure to enjoy your time--and burn some calories while you’re at it!",
    instruction: "- Grab a bicycle helmet, a pair of tennis shoes, and check the air pressure of your tires\n- Map an interesting and safe route on your phone\n- Have a fun ride",
    tips: "- Most road bike tires should be inflated to 80-140 psi, while hybrid tires only require 60-70 psi\n- Bikes must follow the same rules of the road as cars, so remember to come to a full stop at stop signs",
  },
  9: {
    name: 'yoga',
    // number: 9,
    category: 'exercise',
    points: 500,
    description: "Yoga is an exercise discipline which includes breath control, simple meditation, and the adoption of specific bodily postures. It is widely practiced for health and relaxation. Enjoying the practice outdoors is one of the best ways to connect your mind to the environment that we call home.",
    instruction: "- Lay out a thick mat outside. Test out that your bones will not be in pain when you put your knees or elbows on the matt. Move to a grass area for more give.\n- Follow a professional’s guidance: Find a guided class on youtube that fits your timeframe\n- Enjoy!",
    tips: "Be kind to yourself. Everything takes practice to become good at it. So if you fall out of some poses or find that you cannot reach your toes at times, it is no problem. The more you practice, the more progress you will see.",
  },
  10: {
    name: 'shoot hoops',
    // number: 10,
    category: 'exercise',
    points: 400,
    description: "Lace up your tennis shoes, grab a headband, and hit the court! It’s time to channel your inner NBA star and let it fly from deep.",
    instruction: "- Grab your active shoes and a basketball\n- Find a park, gym, or other local basketball court\n- Shoot around, chase your rebounds, and work up a sweat",
    tips: "If you don’t, many rec centers and gyms have basketballs available for use--just ask!",
  },
  11: {
    name: 'outdoor meditation',
    // number: 11,
    category: 'mental',
    points: 200,
    description: 'The goal of this activity is to connect your mind with your body to increase mental and physical peace. Such moments of calmness are necessary for busy students who are continually jumping from one activity to the next. In fact, many say that meditation has taught them to live in the present and how to make more of their lives feeling more relaxed!',
    instruction: '- Find a place outside that feels calm and quiet to you. Set a time limit and try to focus on how your body is feeling. Feel your breath and pay attention to how it is affecting you; how is it moving?. If your mind wonders, be kind to yourself and simply direct your attention back to your breath.',
    tips: '- There are many guided meditation sessions on youtube, check them out!\n- If possible, meditate in the morning. This can be a wonderful way to start the day as you are likely to feel more awake and refreshed, setting yourself up for a  mindful day.\n- It’s recommended that if you meditate regularly, you do so in the same place every time to help your mind shift into the proper mindset easier.',
  },
  12: {
    name: 'nature scavenger hunt',
    // number: 12,
    category: 'mental',
    points: 300,
    description: 'A scavenger hunt is a fun way to remind yourself to recognize, appreciate, and enjoy all the amazing nature gifts that are all around us. Take a stroll outside while looking for the scavenger hunt items. Who knows what you will find!',
    instruction: '- For this activity, you will need to lace up your favorite comfortable boots, grab a pen or a pensil, and a scavenger hunt form from:\n https://www.doinggoodtogether.org/projects/try-a-nature-scavenger-hunt \nEnjoy!',
    tips: '- Make sure to check the weather before heading outside!\n- If you are wandering out to woodsy areas, make sure to protect yourself from sun, bugs, and poisonous plants.',
  },
  13: {
    name: 'read book outside',
    // number: 13,
    category: 'mental',
    points: 200,
    description: "This activity is as straightforward as it sounds: grab a book, find a nice spot outside, and enjoy your book and the outdoors simultaneously.",
    instruction: "- Find a book of interest \n- Find a good spot outside (on the grass, on your porch, on a hammock, at an outdoor seat at a cafe, wherever you feel comfortable)\n- Read and enjoy",
    tips: "Mind your posture while reading. Reading with your head directly above a book overtime may lead to neck and back pains; instead, try reading in a more upright position.",
  },
  14: {
    name: 'Do HW outside',
    // number: 14,
    category: 'mental',
    points: 300,
    description: "Homework is no excuse to stay inside! As a college student, homework is unavoidable so why not tackle your assignments while enjoying the outdoors?",
    instruction: "- Check the weather before heading out to ensure that your experience outdoors will be pleasant\n- Check ahead if the location you are going to has picnic tables or if you need to bring a towel to sit on\n- Grab your laptop and any books you might need and enjoy the location of your choice! Happy studying!",
    tips: "- Bring noise canceling earphones. College campus often comes with unpredictable noises and lots of activity. Noise canceling earphones will help you stay focused\n- If you get stressed, draw your attention to the nature around you. By watching the wind move leaves on the tree in front of you, you are likely to return to a peaceful state of mind quicker\n- If it is extra sunny outside, grab an extra towel to drape over your head and your laptop to hide from the glare",
  },
  15: {
    name: 'Bird watching',
    // number: 15,
    category: 'mental',
    points: 300,
    description: "In the mood for getting some fresh air and appreciating nature, but not intense exercise? Bird watching will help you enjoy the outdoors to whatever extent you desire and encourage you to observe the scenery and life in greater detail than you might normally.",
    instruction: "- For beginner bird-watchers, Audubon New York has this handy guide: https://ny.audubon.org/news/bird-watching-101-guide-beginners",
    tips: "- If you want a little more purpose behind your experience, consider downloading one of the education mobile apps mentioned in the Beginner’s Guide mentioned previously or the Audubon Society’s own Bird Guide App: https://www.audubon.org/app#:~:text=The%20Audubon%20Bird%20Guide%20is,find%20new%20birds%20near%20you\n- You may also want to challenge yourself to photograph, draw, describe, record as many birds as you can during this activity",
  },
};

export function getActInfo() {
  return actDict;
}
